### ISSUE TITLE
Fix broken mmaps and improve mmaps in general

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/tswow#137]
mmap generation leaves a lot to be desired, it would be especially good to be able to selectively generate maps and to do so from a folder instead of MPQ.

**Comment by TesterWoWDev** [comment]
just as a note, mmap generator already can be done by a single mapID via a command line parameter

**Comment by ihm-tswow** [comment]
Fix: https://github.com/tswow/tswow/commit/11fd48fec6b655fcbcd5a362c0693aca9a06b900
