### ISSUE TITLE
Datascript changes takes two builds to show on client

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#163]
**Describe the bug**
It takes running datascripts twice to see results on the client.

**To Reproduce**
1. Create a data script with a visible client effect
2. Build datascripts once
3. Log in to the game
4. No changes are visible

**Expected behavior**
It takes one run to see results on the client

**Comment by ihm-tswow** [comment]
This may be related to watching client files through vscode, I noticed significant instability with building client files on debian until I removed the patch directory from my workspace. Maybe it's trying to remove the patch directory itself?
