### ISSUE TITLE
New positions file breaks for some users

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/tswow#181]
Seems like some users can't access the new positions file. It's just empty when they open it, even though the clipboard works fine.

**Comment by ihm-tswow** [comment]
@tswow-admin test this please

**Comment by tswow-admin** [comment]
I cannot reproduce this, both the file and clipboard updates correctly.

**Comment by ihm-tswow** [comment]
I asked the discord before and nobody else could reproduce. Reopen if we get more reports.
