### ISSUE TITLE
livescripts: better crash message when accessing invalid entities on CreatureID/SpellID etc.

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/tswow#259]
currently it just crashes with no message

**Comment by tswow-admin** [comment]
What exactly do you mean by accessing on CreatureID/SpellID? @ihm-tswow

**Comment by ihm-tswow** [comment]
```ts
events.CreatureID.OnUpdateAI(someInvalidId,()=>{})
events.SpellID.OnCast(someInvalidId,()=>{})
```

**Comment by ihm-tswow** [comment]
This seems to have been fixed, I assume it's this: https://github.com/tswow/tswow/commit/fd5605773e23c7c425166e609f2cddb73082e158
