### ISSUE TITLE
datascripts: id generation is comically broken

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/tswow#367]
```ts
let v = new StaticIDGenerator('test-table1',100)
let q = new StaticIDGenerator('test-table2',100)
console.log('v:',v.dynamicId())
console.log('q:',q.dynamicId())
```

```
v:100
q:101
```

can't make this shit up. wotlkdata Allocators _aren't table separated_ 🤦 

the fix isn't hard at all, but how this has managed to stay undetected for 9 months by anyone is the funniest shit. I can't even think of any unresolved scenario where this could have been the culprit

**Comment by ihm-tswow** [comment]
did I say allocators, I meant allocator, because there's just one

**Comment by tswow-admin** [comment]
i uh

**Comment by ihm-tswow** [comment]
> i uh

fix your pfp
