### ISSUE TITLE
Add database formulas for stat coefficients

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#37]
Currently, stat coefficients are hardcoded into TrinityCore. We want to move these to the database so we can both modify existing classes and add new ones.

The stats I could find in TrinityCore are:
```
diminishingReturns
miss_cap
parry_cap
dodge_cap
dodge_base
crit_to_dodge
```

We need to 
- [ ] Create a new database table `class_ratings(int,int,int)`
- [ ] Add lookups for this new database to both StatSystem.cpp and Player.cpp
- [ ] Add type definitions to wotlkdata/sql
- [ ] Add module to stdlib/classes

**Comment by ihm-tswow** [comment]
These were added as livescript events instead of the old interpreter
