### ISSUE TITLE
[0.13] Incorrect Unit Flags Output

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#377]
**Describe the bug**

Just noticed this in TC output: `Table creature_template lists creature (Entry: 45135) with disallowed unit_flags2 1024, removing incorrect flag.`

I'm 99% sure these flags were right pre-0.13

This should be producing 33555200 in `unit_flags` which it is correctly, and 2048 in `unit_flags2` according to [TC Docs](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/1200128167/creature+template+3.3.5a)

Instead `unit_flags2` is getting 1024 UNIT_FLAG2_DISARM_RANGED

**To Reproduce**
```ts
export const BOUNDARY_BUNNY = std.CreatureTemplates.create('project-epoch', 'boundary-bunny', 721)
    .Name.enGB.set('Boundary Bunny - Hidden')
    .UnitFlags.clearAll()
    .UnitFlags.ImmuneToNPC.set(true)
    .UnitFlags.ImmuneToPC.set(true)
    .UnitFlags.NotSelectable.set(true)
    .UnitFlags.RegeneratePower.set(true)
    .FlagsExtra.set(128);
```

**Expected behavior**

**Additional Context**
Add any other context or screenshots about the issue here.

**Comment by ihm-tswow** [comment]
becomes 33555200 and 1024 with the mask update, so I assume it's been fixed

**Comment by kaytotes** [comment]
1024 would be incorrect. flags2 should be 2048

![image](https://user-images.githubusercontent.com/7526918/137536922-bef2d5aa-518a-4538-87b7-ca53a6904c0d.png)

**Comment by kaytotes** [comment]
Actually, i'm getting this result with 0.12

```ts
console.log(std.CreatureTemplates.create('test-module', 'flags-test').UnitFlags.clearAll().UnitFlags.RegeneratePower.mark().row.unit_flags2.get());
```

```
1024
```

And the same result with 0.13

```ts
console.log(std.CreatureTemplates.create('test-module', 'flags-test').UnitFlags.clearAll().UnitFlags.RegeneratePower.set(true).row.unit_flags2.get());
```

```
1024
```

So I guess this isn't an issue with generating the masks themselves, that hasn't changed (or has been broken for a long time). 

Why TC is now reporting this as an issue and why their docs don't match this output is maybe another question.

**Comment by kaytotes** [comment]
Reproducable in 0.13.1

```ts
import { std } from "tswow-stdlib";

console.log("Hello from test-module data script!");

export const BOUNDARY_BUNNY = std.CreatureTemplates.create('test-module', 'boundary-bunny', 721)
    .Name.enGB.set('Boundary Bunny - Hidden')
    .UnitFlags.clearAll()
    .UnitFlags.REGENERATE_POWER.set(true);

console.log(BOUNDARY_BUNNY.UnitFlags.objectify());
```

TC output states the same.

**Comment by ihm-tswow** [comment]
Yeah sorry, I read your post wrong. I found the issue, there is a gap in the table (goes from 256 to 1024), so it's an issue local to UnitFlags
