### ISSUE TITLE
[0.13]: Map generation hanging.

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#378]
**Describe the bug**
When generating ADT's for a new map the process hangs. 

**To Reproduce**
```ts
export const TESTING_MAP = std.Maps.create('test-module', 'testmap')
    .Name.enGB.set('Testing Map')
    .HordeDescription.enGB.set('For the Horde')
    .AllianceDescription.enGB.set('For the Alliance')
    .Directory.set('testmap')
    .IsPVP.set(0)
    .InstanceType.Party.set()
    .MaxPlayers.set(5)
    .Expansion.set(0)
    .MapFiles.add('testmap', [
        [0, 0, 0, 0, 'testmap']
    ]);
```

Output hung at `Reading ADT offsets` for 20 minutes before I terminated it. Nothing spat out into assets directory.

**Expected behavior**
Files to be created in assets directory with adt and wdt etc.

**Additional Context**
Add any other context or screenshots about the issue here.

**Comment by ihm-tswow** [comment]
Cannot reproduce this

**Comment by kaytotes** [comment]
Will test again when the new repack comes out with a fresh module.

**Comment by kaytotes** [comment]
Re-tested this again with 0.13.1 in a freshly generated module with none of my existing code. 

Same issue, hanging at reading offsets.

**Comment by kaytotes** [comment]
Worked once ihm gave me the `source.adt` in `bin` I guess that needs including in future releases.
