### ISSUE TITLE
[0.13]: Buggy gossip remains

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#379]
**Describe the bug**
Had very similar issues on 0.12 but seems it's still present if not somehow worse. Gossips don't match up with the right npc / are overwriting each other somehow.

I do need to update the gossip change for the 2nd npc to the new syntax but I don't _think_ that would explain this behaviour.

NPC A:

```ts
export const MURUN_GOLDROAR = std.CreatureTemplates.create('epoch-core', 'murun-goldroar', 1472);

MURUN_GOLDROAR
    .Name.enGB.set('Murun Goldroar')
    .Subname.enGB.set("")
    .Level.Min.set(21)
    .Level.Max.set(21)
    .Icon.setSpeak()
    .NPCFlags.ClassTrainer.set(false)
    .NPCFlags.Gossip.set(true)
    .Gossip.modNew((gossip) => {
        gossip
            .Text.add({enGB: "How on Azeroth did you get up here $N?"}, undefined, 1);
    })
```

NPC B:
```ts
/** Add to thunderbluff class trainer gossip. */
SQL.gossip_menu_option.find({ MenuID: 1949, OptionID: 7 })
    .ActionPoiID.set(502);

const GOSSIP_TEXT = 'Nunle Skydrifter can be found in Grommash hold informing the war chief of their newfound power.';

/** Orgrimmar already has a paladin trainer as a BE, update the gossip text. */
SQL.npc_text.find({ ID: 10843})
    .text0_0.set(GOSSIP_TEXT)
    .text0_1.set(GOSSIP_TEXT);

SQL.broadcast_text.find({ ID: 20975})
    .Text.set(GOSSIP_TEXT)
    .Text1.set(GOSSIP_TEXT);
```

![image](https://user-images.githubusercontent.com/7526918/137217764-beffe903-7384-4901-8fc3-872f2c02907d.png)

**Comment by ihm-tswow** [comment]
Cannot reproduce, the correct text shows up for me

**Comment by kaytotes** [comment]
I will double check this with the next repack and see if maybe my code itself is causing the issue elsewhere.

**Comment by kaytotes** [comment]
Can not reproduce with a much smaller testing module on 0.13.1. Added numerous gossips and modded existing ones.
