### ISSUE TITLE
0.13]: Areas potential off by one error

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#381]
**Describe the bug**

```
Player 'Arlad' (GUID Full: 0x0000000000000004 Type: Player Low: 4) discovered unknown area
```

Server has no idea where the player is in my custom area.

This _feels_ like it should be some kind of config fuck up on my side as `DataDir` appears to be pointed correctly: `DataDir = "E:\Dev\WoW\tswow-prerelease\coredata\datasets\default"`

Edited existing areas are working client side so maybe this issue is entirely server side?

Eg this renamed area in EotS works fine client side and I guess server side too since the ID didn't change.

![image](https://user-images.githubusercontent.com/7526918/137219760-7b705eaa-2cf2-465e-b643-29fbb2dc0887.png)

```
Command: gps [Player: Thorisx (GUID Full: 0x0000000000000003 Type: Player Lo
w: 3) (Account: 1) X: -8456.794922 Y: -399.286346 Z: 190.713531 Map: 0 (Eastern Kingdoms) Area: 4989 (Unknown) Zone: Unknown Selected:  (GUID Full: 0x0000000000000000 Type: None Low: 0)]
>
```

areas.json

```
{
    "epoch-core:northshire-falls-area": 4988
}
```

ids.txt

```
AreaTable|epoch-core:northshire-falls-area|4988|4988|
AreaTableExplore|epoch-core:northshire-falls-area-bit|3618|3618|
```

![image](https://user-images.githubusercontent.com/7526918/137295878-2bcf0770-357c-4eb5-bc8c-d69990ac062e.png)

Maps and vmaps freshly extracted

**To Reproduce**

**Expected behavior**

**Additional Context**
Add any other context or screenshots about the issue here.

**Comment by ihm-tswow** [comment]
Tried this but cannot reproduce, the area in your screenshot says "Goblin enclave", but this is not the area in your ids.txt. 

What areas are involved and what are their ids?

**Comment by kaytotes** [comment]
@ihm-tswow Closing this. 

Turned out to be my adt's from 0.12 still had the old id and obviously 0.13 didn't really know to correct that. I resolved this by first re-painting my area id in noggit to confirm. 

Then manually filled in `areas.json` for all others.

Probably worth that being included in any future "upgrade guide".
