### ISSUE TITLE
[0.13] livescripts: Getting Players and GObjects in range not working.

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#389]
**Describe the bug**
When trying to get players in range it finds nothing. 

Same applies to finding game objects in range eg

```ts
    let fires = creature.GetGameObjectsInRange(150, EPOCH_CORE_FIRE_DOOR_GOBJECT, 0);
    let collisions = creature.GetGameObjectsInRange(150, EPOCH_CORE_INVISIBLE_DOOR_GOBJECT_ONYXIA, 0);
```

**To Reproduce**

```ts
/**
 * Entrypoint to the script.
 * @param events 
 */
export function TestCreature(events: TSEventHandlers) {
    events.CreatureID.OnJustEnteredCombat(299, (creature) => {
        let players = creature.GetPlayersInRange(100, 1, 1);

        console.log(`Players Found: ${players.length}`);
    });
}
```

Applied to Diseased Young Wolf in human start area.

**Expected behavior**

**Additional Context**
Add any other context or screenshots about the issue here.

**Comment by ihm-tswow** [comment]
I can reproduce this for both players and gameobjects

**Comment by ihm-tswow** [comment]
Does not seem to affect `GetNearestPlayer`, TSArray bug?

**Comment by ihm-tswow** [comment]
Does not seem to be any issues adding to tsarrays normally, and I can't see how it would break in the TSWorldObject code.

Might be related to this https://github.com/tswow/TrinityCore/commit/59391cfab925013f71beb12a314594b448a4e68c

or https://github.com/tswow/TrinityCore/commit/ca740ce4f9a1e6fe9d83a1ae27b8b316753b80e0

**Comment by ihm-tswow** [comment]
The issue is not with TSArrays, nothing is added in the searcher object

**Comment by ihm-tswow** [comment]
found it, will push fix later today

```
    for (PlayerMapType::iterator itr=m.begin(); itr != m.end(); ++itr)
        // @tswow-begin
        if (!itr->GetSource()->InSamePhase(i_phaseMask, i_phase_id))
        // @tswow-end
            if (i_check(itr->GetSource()))
                Insert(itr->GetSource());
```
