### ISSUE TITLE
datascripts: Ability to specify the say type for `setTalk` smart action.

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#398]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to use the various types of talking to the player. 
![image](https://user-images.githubusercontent.com/7526918/142049106-7e7e9157-a2a0-4c9c-a641-9d53ceb45d28.png)

https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130007/creature+text#creature_text-groupid

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ihm-tswow** [comment]
done in https://github.com/tswow/tswow-stdlib/compare/faa8b38a0389...fdc41aecf1be

will be in 0.13.3, uses a separate action called `setTalkGroup` 

```ts
        script.Action.setTalkGroup(group=>{
            group
                .addMod(text=>{
                    text.Text.set({enGB:'Message1'})
                        .Probability.set(50)
                        .Type.YELL.set()
                })
                .addMod(text=>{
                    text.Text.set({enGB:'Message2'})
                        .Probability.set(50)
                        .Type.set('SAY')
                })
        })
```
