### ISSUE TITLE
Fix scripting API

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#44]
The scripting API has a bunch of bugs since we moved it from AzerothCore. 

- Creature/Spell scripting is not enabled

- Some API functions/events do not work

**Known functions that do not work**
- ~TSPlayer#AddQuest~
- ~TSPlayer#ResetTypeCooldowns~
- ~TSItem#GetItemLink~
- ~TSCreature#GetAITarget~
- ~TSWorldObject#**Anything about nearby objects**~

**Comment by tswow-admin** [comment]
Something like this for things with IDs:

```c++
EVENT_TYPE(SpellOnCast,Spell);

class TSSpellEvent {
    EVENT_TYPE(SpellOnCast);    
};

// in struct TSEvents
std::map<number,SpellEvent> spells;


// in struct SpellInfo
TSSpellEvent event;

// in Spell#CallOnCast or whatever it's called
FIRE_MAP(event,SpellonCast,this);

```

**Comment by tswow-admin** [comment]
Basic spell scripting added: https://github.com/tswow/TrinityCore/commit/9fdf5fcabaf8f4fff6f013ea55909e9355b10d68

**Comment by ihm-tswow** [comment]
~Unit#SetName~

**Comment by ihm-tswow** [comment]
~Player#GiveXP~

**Comment by ihm-tswow** [comment]
~Anything relating to Groups and LFG~

**Comment by ihm-tswow** [comment]
All todos have been addressed and compiles, open a new issue if there is anything else missing
