### ISSUE TITLE
Adding a new Creature Type doesn't work in game

### ISSUE THREAD

**Issue by ghost** [tswow/tswow#482]
Listing this as a Feature Request because it seems more like one to me, but maybe it should be changed to bug report?

When you create a new Creature Type, TSWoW lets you do so very easily, but when you summon the creature in game it appears as a Humanoid. After doing some digging it seems to be defined in `\src\server\shared\SharedDefines.h` of TrinityCore under the enum "CreatureType", and isn't wholly reliant on the DBC that TS is able to edit.

```ts
import { std } from "tswow-stdlib";
import { Ids } from "tswow-stdlib/Misc/Ids";

std.DBC.CreatureType.add(Ids.CreatureType.id('epoch-core','aberration-type'))
    .Name.enGB.set('Aberration')

std.CreatureTemplates.create('epoch-core','aberration-test',3244)
    .Name.enGB.set('Aberration Test')
    .Type.ABERRATION.set()
```

**Comment by ihm-tswow** [comment]
General note: we can check if this is handled correctly in the core by accessing `creature.GetTemplate().GetType()`. It can also be checked with the `UnitCreatureType` function in addons

**Comment by ihm-tswow** [comment]
Sorry, just noticed what's wrong. 

The `ABERRATION` field in our `CreatureType` is not a valid entry in the DBC (it's probably some cata+ value) so it should not be used, i'll remove it in a patch. Try instead modifying your script like this:

```ts
const MY_ABERRATION = std.DBC.CreatureType
    .add(Ids.CreatureType.id('epoch-core','aberration-type'))
    .Name.enGB.set('Aberration')

std.CreatureTemplates.create('epoch-core','aberration-test',3244)
    .Name.enGB.set('Aberration Test')
    .Type.set(MY_ABERRATION.ID.get())
```

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/4321583/158691257-5007703d-6bae-4ec2-84b4-baecbfb2c03d.png)

That works! Feels silly that I didn't even notice that I had typed a built in number and didn't actually get my DBC entry. It is indeed a creaturetype from Cataclysm normally. Thanks!
