### ISSUE TITLE
Custom pets gives error in TrinityCore

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#55]
Following code creates a working spell
```
export const SUMMON_HOGGER = 
    std.Spells.create('tswow-introduction', 'summoning-spell', 688)
            .Effects.get(0).MiscValueA.set(448).up()
```

But when logging in after summoning it, TrinityCore gives the following error:

```
Unknown type pet 448 is summoned by player class 12
```

The pet still works fine afterwards though.

**Comment by ihm-tswow** [comment]
was fixed here, it's a hardcoded check https://github.com/tswow/TrinityCore/commit/18ef7f4654d21bc9fc4ed84ff92d379becda47a3
