### ISSUE TITLE
The flags (512) used for TotemCreatures might have unknown behaviors

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#59]
I don't know what this flag actually means, I just saw another row use it so I did too because there is no overlap between them. It doesn't seem to be used for anything on the server, but the client might do something.

From TrinityCore:

```c++
if (properties->Flags & 512) // Mirror Image, Summon Gargoyle
    mask = UNIT_MASK_GUARDIAN;
break;
```

**Comment by ihm-tswow** [comment]
Not an issue
