### ISSUE TITLE
Autolearning languages not working

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#74]
**Describe the bug**
It's not possible to autolearn languages

**To Reproduce**

Give pirate language to mage class:
```
export const PIRATE_LANGUAGE = std.Languages
    .create('tswow-necromancer','pirate_language',{enGB:'Pirate'},[],[8])
    .Name.set({enGB: 'Pirate'})
    .addWords(['ahoy','matey','deck','aye','booty','bounty','bucko','chanteys','loot',
        'me','rum','savvy','ho','ye','yo ho ho','tah','pirate','\'tis'])
```

**Expected behavior**
The class should learn the language when the character is created

**Comment by ihm-tswow** [comment]
This has been completely overhauled and has worked for a long time
