### ISSUE TITLE
Lua livescripts: CastCustomSpell crashes server

### ISSUE THREAD

**Issue by gigi-fernandez** [tswow/tswow#804]
**Description**
CastCustomSpell crashes whenever called (if script was transpiled into Lua). The crash log suggests that it calls StopSpellCast 8 times, followed by ApplySpellMod once, which crashes the server.

**To Reproduce**
Call CastCustomSpell with any values (default or explicit) from livescripts (only for lua compilations)

**Comment by ihm-tswow** [comment]
can you show how you call this and with what spell? i get a very different error when trying to use it in lua

**Comment by ihm-tswow** [comment]
seems to be some issue with the overloads, but the following seems to work without issues:

```
        if(player.GetSelection().IsUnit())
        {
            // the 'player.GetItemByEntry(0)' will just send a null item
            player.CastCustomSpell(player.GetSelection(),133,true,0,0,0,player.GetItemByEntry(0),0);
        }
```

your issue might be spell-specific or caused by recursive behavior depending on what event you're listening to

**Comment by gigi-fernandez** [comment]
The following snippet is from an addon message event being sent only once. Script (there is no event affected by the spellcast).

```ts
const Q = QueryCharacters(`SELECT * FROM item_storage WHERE (guid = ${item_guid} AND owner_guid = ${npc_guid});`)
            while (Q.GetRow()) {
                console.log("Retrieving item") // only prints out once
                player.CastSpell(player, 11, false)
                player.CastCustomSpell(player, 11, false, 10, 10, 10, undefined, 0)
            }
```
            
Crash log:
`
Address   Frame     Function      SourceFile
00007FFD2F403C66  000000C4476FD5A0  ??$ApplySpellMod@M@Player@@QEBAXIW4SpellModOp@@AEAMPEAVSpell@@@Z+203B6
00007FFD302327C1  000000C4476FD630  ?StopSpellCast@TSUnit@@QEAAXI@Z+21061
00007FFD3022D44A  000000C4476FD6C0  ?StopSpellCast@TSUnit@@QEAAXI@Z+1BCEA
00007FFD3022D2BA  000000C4476FD740  ?StopSpellCast@TSUnit@@QEAAXI@Z+1BB5A
00007FFD3022D1DD  000000C4476FD7C0  ?StopSpellCast@TSUnit@@QEAAXI@Z+1BA7D
00007FFD30235530  000000C4476FD830  ?StopSpellCast@TSUnit@@QEAAXI@Z+23DD0
00007FFD30230133  000000C4476FD8A0  ?StopSpellCast@TSUnit@@QEAAXI@Z+1E9D3
00007FFD302336D1  000000C4476FD900  ?StopSpellCast@TSUnit@@QEAAXI@Z+21F71
00007FFD3021CA1F  000000C4476FD960  ?StopSpellCast@TSUnit@@QEAAXI@Z+B2BF
00007FFD2F15FBEB  000000C4476FD9C0  ?UpdateTimer@SmartScript@@QEAAXAEAUSmartScriptHolder@@I@Z+2BBB
`

**Comment by ihm-tswow** [comment]
replacing your code with `player.CastCustomSpell(player, 11, false, 10, 10, 10, player.GetItemByEntry(0), 0)` lets me cast 11 without issues. seeing you don't have the problem I have with sending undefined for the item, i assume you're on a slightly older revision. what version are you using? (`revision` command in console)

**Comment by gigi-fernandez** [comment]
Revision 8cdb76e
I will try to use GetItemByEntry, although it does feel a bit unintuitive. Is that the default already?

**Comment by ihm-tswow** [comment]
it's definitely a bug that it doesn't accept it without that, just need to figure out why it doesn't like that. seeing nothing that should've changed this it might be down to the built type causing the error to behave differently

**Comment by gigi-fernandez** [comment]
It does work with GetItemByEntry 👍

**Comment by ihm-tswow** [comment]
@MisterFuture fixed properly here https://github.com/tswow/tswow/commit/d8f73605f3a2475e8c9df498285a2a569d0df5ec
