### ISSUE TITLE
datascripts: std.Taxi Poor Performance

### ISSUE THREAD

**Issue by kaytotes** [tswow/tswow#840]
From what I can tell using `--profile-scripts` there seems to be a pretty bad performance issue with std.Taxi

```
world\taxis\the-harborage.ts: 2265ms
world\taxis\anje-watha.ts: 8757ms
world\taxis\springsocket.ts: 13000ms
```

The springsocket.ts file creates 14 paths, anje-watha creates 9, the-harborage creates 3. Not far off 1 second per taxi. 

https://gist.github.com/kaytotes/84a0dc77656c9a269fd1cf6893943745

Considering these are DBC operations this feels very slow.

`createUni` used for transports seems to be a bit more performant but still relatively slow for inserting a handful of rows imo.

```
world\transports\lady-mehley.ts: 266ms
world\transports\bravery.ts: 268ms
```

https://gist.github.com/kaytotes/90acc97e656073315763ff6c950e4270

**Comment by ihm-tswow** [comment]
improvement here: https://github.com/tswow/tswow/commit/14b04100bb45613560361eaa5bc49a6932cc600b

not a complete fix, the way we do this is still suboptimal and probably patchy with broken or deleted paths

**Comment by ihm-tswow** [comment]
Did the above fix the performance issues or do you still experience those? If not, I think we can close this and make a new one for potential issues dealing with gaps/deleted rows

**Comment by kaytotes** [comment]
I do remember testing this at the time and seeing an improvement but for reasons I can't remember ended up rewriting to using our own std for this.

https://gist.github.com/kaytotes/b156b926af38bae606088947a1f1b976

Up to you if you want to close.
