### ISSUE TITLE
Build full crashes

### ISSUE THREAD

**Issue by ThoorAdam** [tswow/tswow#845]
**Describe the bug**
`build full` command crashes following the compile guide on the wiki.

![image](https://github.com/tswow/tswow/assets/17762966/db370430-47e7-4033-86f2-50ebb12b618d)

**To Reproduce**
1. Clone repo as in tutorial.
2. npm i
3. npm run build-interactive
4. build full

**Expected behavior**
Successfull compilation

**Additional Context**

**Comment by dual002** [comment]
I encountered the same problem, which occurred after upgrading VS to 17.10.1

**Comment by kaytotes** [comment]
https://github.com/TrinityCore/TrinityCore/issues/29999

https://github.com/TrinityCore/TrinityCore/commit/d8240fb513fc18ee9bac067f8333aab1d96005d9

Either manually patch that in your source or wait for me to fix upstream in TS-WoW soon

**Comment by ihm-tswow** [comment]
This was merged into tswow as of https://github.com/tswow/tswow/commit/50dd96484ef6cf0431efae9bf9bee2dfbcf93bb7
