### ISSUE TITLE
wotlkdata gets unlinked during startup

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/tswow#86]
**Describe the bug**
At some point during startup, node_modules/wotlkdata is unlinked and breaks all the modules. This happened after updating to v0.5

node version is v15.5.0
npm version is v6.14.9
tswow version is v0.5

**Expected behavior**
wotlkdata shouldn't be unlinked at all during startup

**Comment by ihm-tswow** [comment]
dead Today at 10:13 PM: 

> a workaround that seems to be working great for now is just saving it as a package.json dependency: npm i -S .\bin\scripts\tswow\wotlkdata

**Comment by ihm-tswow** [comment]
Same issue with the stdlib now, I think we need those commands for every single module we create

**Comment by tswow-admin** [comment]
Attempted fix: https://github.com/tswow/tswow/commit/3fb21aec76bb16e5eeb839e22c9dd69444b21f45
