### ISSUE TITLE
tswow gets stuck if the worldserver crashes during startup

### ISSUE THREAD

**Issue by ihm-tswow** [tswow/tswow#89]
**Describe the bug**
if the worldserver crashes during startup, tswow gets stuck because it's waiting for the finish message.

**To Reproduce**
divide by zero in a script file or whatever to crash the server

**Expected behavior**
if the worldserver crashes during startup, control should be returned to the terminal

**Comment by tswow-admin** [comment]
Fixed in https://github.com/tswow/tswow/commit/2adbb199a7aca0e51222df9d3ee8887b2599a0ca, we shouldn't even wait for it in the first place.
